apps:
  - chrome
  - safari
  - firefox
  - slack
  - docker
  - outlook
  - teams
  - vscode
  - zoom
  - skype
  - k9s
  - jira
  - spotify
  - notion
  - trello
  - thunderbird
  - postman
  - discord
  - webstorm
  - pycharm
  - intellij
  - eclipse
  - android-studio
  - sublime-text
  - gitkraken
  # - gitbash
  - iterm
  - alacritty
  - zsh
  - bash
  - powershell
  - terminal
  - obs
  - vlc
  - gimp
  - photoshop
  - figma
  - canva
  - dropbox
  - onedrive
  - google-drive
  - aws-cli
  - azure-cli
  - kubectl
  - helm
  - terraform
  - ansible
  - chef
  - puppet
  - gradle
  - maven
  - cmake
  - envoy
  - nginx
  - glop
  - nvm
  - npm
  - yarn
  - pip
  - conda
  - cargo
  - gem
  - bundler
  - composer
  - pub
  - sbt
  - leiningen
  - cocoapods
  - spm
  - apt
  - yum
  - dnf
  - pacman
  - brew
  - chocolately
  - winget
  - snap
  - flatpak
  - rpm
  - emerge
  - opkg
  - zypper
  - portage
  - bazel
  - buck
  - meson
  - ninja
  - clion
  - visual-studio
  - qt-creator
  - xcode
  - codeblocks
  - dev-cpp
  - mingw
  - g++
  - clang++
  - valgrind
  - gdb

# apps:
#   - chrome
#   - safari
#   - firefox
#   - slack
#   - docker
